---
version: '2'

services:
    app:
        build: app
    # newer version of docker do not require links for services. 
    # docker runs a dns server to look up services. 
    proxy:
      build: proxy
    #   expose:
    #   - 3000
      ports: 
      - "80:80"
    redis:
        build: redis
        ports: ["6379:6379"]
